apiVersion: v1
kind: Pod
metadata:
  name: liveness
  labels:
    app.kubernetes.io/name: liveness
spec:
  containers:
    - name: web
      image: startkubernetes/app-health:0.1.0
      ports:
        - containerPort: 3000
      livenessProbe:
        httpGet:
          path: /healthz
          port: 3000
        initialDelaySeconds: 3
        periodSeconds: 1
